# Build in this directory via:
#
# pack buildpack package ekanderson/klr-buildpack:0.0.1 --config .\package.toml --publish

api = "0.5"

[buildpack]
  id = "ekanderson/klr-buildpack"
  name = "Demo Knative Lambda Runtime Buildpack"
  version = "0.0.4"

[metadata]
  include-files = ["buildpack.toml"]


## I would like to write the following, but it appears that you can't meta-meta-builpack...
# [[order]]

# [[order.group]]
# id = "packeto-community/python"
# version = "0.5.0"

# [[order.group]]
# id = "evankanderson/klr-buildpack-addin"
# version = "0.0.1"

# PIP first
# Copied from https://github.com/paketo-community/python
[[order]]

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    version = "0.7.3"

  [[order.group]]
    id = "paketo-buildpacks/pip"
    version = "0.6.0"

  [[order.group]]
    id = "paketo-buildpacks/pip-install"
    version = "0.2.0"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.6.2"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "4.4.1"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "3.2.2"

  [[order.group]]
    id = "ekanderson/klr-addin"
    version = "0.1.0"

# Then pipenv
# Copied from https://github.com/paketo-community/python
[[order]]

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    version = "0.7.3"

  [[order.group]]
    id = "paketo-buildpacks/pip"
    version = "0.6.0"

  [[order.group]]
    id = "paketo-buildpacks/pipenv"
    version = "0.2.1"

  [[order.group]]
    id = "paketo-buildpacks/pipenv-install"
    version = "0.2.3"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.6.2"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "4.4.1"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "3.2.2"

  [[order.group]]
    id = "ekanderson/klr-addin"
    version = "0.1.0"

# Then without packages
[[order]]

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    version = "0.7.3"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.6.2"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "4.4.1"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "3.2.2"

  [[order.group]]
    id = "ekanderson/klr-addin"
    version = "0.1.0"
